Update probarcodigo.yml
veamos las prueas

diff --git a/.github/workflows/probarcodigo.yml b/.github/workflows/probarcodigo.yml
--- a/.github/workflows/probarcodigo.yml
+++ b/.github/workflows/probarcodigo.yml
@@ -24,4 +24,12 @@ jobs:
     - name: Compilar
       run: dotnet build ./anamportalboletas/anamportalboletas.sln --no-restore 
     - name: Test
-      run: dotnet test ./anamportalboletas/Anam.BoletasAduanales.1.BoletasPruebasUnitarias/Anam.BoletasAduanales.1.BoletasPruebasUnitarias.csproj  --no-build --verbosity normal 
+      run: dotnet test ./anamportalboletas/Anam.BoletasAduanales.1.BoletasPruebasUnitarias/Anam.BoletasAduanales.1.BoletasPruebasUnitarias.csproj  --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
+    - name: Reporte de pruebas
+      uses: dorny/test-reporter@v1.6.0
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Reporte dotnet     
+        path: test-results.trx   
+        reporter: dotnet-trx
+        fail-on-error: 'true'
